version: '3'
services:
  api:
    image: ereq-server
    build:
      context: .
      dockerfile: Dockerfile-dev
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    env_file: .env

networks:
  backend:
    driver: bridge